package ru.femboypig.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import dev.isxander.yacl3.config.v2.api.ConfigClassHandler;
import dev.isxander.yacl3.config.v2.api.serializer.GsonConfigSerializerBuilder;
import dev.isxander.yacl3.gui.controllers.ColorController;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;

import java.awt.*;
import java.text.DecimalFormat;

public class BrushCC {
    public static final DecimalFormat FORMAT = new DecimalFormat("#.##");


    public static final ConfigClassHandler<SEConfigs> CONFIG = ConfigClassHandler.createBuilder(SEConfigs.class)
            .serializer(config -> GsonConfigSerializerBuilder.create(config)
                    .setPath(FabricLoader.getInstance().getConfigDir().resolve("brushclient.json"))
                    .build())
            .build();

    @SuppressWarnings("deprecation")
    public static Screen configScreen(Screen parent) {
        return YetAnotherConfigLib.create(CONFIG, ((defaults, config, builder) -> builder
                .title(Text.translatable("brushclient.title"))

                // RENDER CATEGORY

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("brushclient.render"))

                        // No Hurt Cam
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.nohurtcam"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.nohurtcam"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.nohurtcam.desc")))
                                        .binding(defaults.hurtCamEnabled, () -> config.hurtCamEnabled, newVal -> config.hurtCamEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Visual Ratio
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.visualratio"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.visualratio"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.visualratio.desc")))
                                        .binding(defaults.visualRatioEnabled, () -> config.visualRatioEnabled, newVal -> config.visualRatioEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.visualratio"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.visualratio.desc")))
                                        .binding(1.78f, () -> config.visualRatio, newVal -> config.visualRatio = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0.5f, 10f)
                                                .step(0.01f))
                                        .build())
                                .build())
                        // Black Pigs
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.blackpig"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.blackpig"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.blackpig.desc")))
                                        .binding(defaults.blackPigEnabled, () -> config.blackPigEnabled, newVal -> config.blackPigEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // FullBright
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.fullbright"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.fullbright"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.fullbright.desc")))
                                        .binding(defaults.fullBrightEnabled, () -> config.fullBrightEnabled, newVal -> config.fullBrightEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // No Armor Render
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.noarmorrender"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.noarmorrender"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.noarmorrender.desc")))
                                        .binding(defaults.NAREnabled, () -> config.NAREnabled, newVal -> config.NAREnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Time Changer
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.timechanger"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.timechanger"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.timechanger.desc")))
                                        .binding(defaults.timeChangerEnabled, () -> config.timeChangerEnabled, newVal -> config.timeChangerEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.render.timechanger"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.timechanger.desc")))
                                        .binding(0, () -> config.timeChanger, newVal -> config.timeChanger = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 18000)
                                                .step(100))
                                        .build())
                                .build())
                        // Render Name
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.rendername"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.rendername"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.rendername.desc")))
                                        .binding(defaults.renderNameEnabled, () -> config.renderNameEnabled, newVal -> config.renderNameEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Animations
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.animations"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.animations"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.animations.desc")))
                                        .binding(defaults.animationsEnabled, () -> config.animationsEnabled, newVal -> config.animationsEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.animations.main"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.animations.desc")))
                                        .binding(defaults.animationsMain, () -> config.animationsMain, newVal -> config.animationsMain = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.animations.off"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.animations.desc")))
                                        .binding(defaults.animationsOff, () -> config.animationsOff, newVal -> config.animationsOff = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.animations.slowAnim"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.animations.desc")))
                                        .binding(defaults.slowAnimations, () -> config.slowAnimations, newVal -> config.slowAnimations = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.render.animations.slowAnim"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.animations.desc")))
                                        .binding(12, () -> config.slowValue, newVal -> config.slowValue = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 50)
                                                .step(1))
                                        .build())
                                .build())
                        // View Model
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.viewmodel"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.items"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(defaults.affectItems, () -> config.affectItems, newVal -> config.affectItems = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.scale"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(1f, () -> config.scale, newVal -> config.scale = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0.1f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.scaleoff"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(1f, () -> config.scaleoff, newVal -> config.scaleoff = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0.1f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.posX"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posX, newVal -> config.posX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.posY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posY, newVal -> config.posY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.posZ"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posZ, newVal -> config.posZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotMainX"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotMainX, newVal -> config.rotMainX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotMainY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotMainY, newVal -> config.rotMainY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotMainY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotMainZ, newVal -> config.rotMainZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotOffX"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotOffX, newVal -> config.rotOffX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotMainY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotOffY, newVal -> config.rotOffY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.rotMainZ"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotOffZ, newVal -> config.rotOffZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(defaults.affectArm, () -> config.affectArm, newVal -> config.affectArm = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.posX"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posArmX, newVal -> config.posArmX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.posY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posArmY, newVal -> config.posArmY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.posZ"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.posArmZ, newVal -> config.posArmZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.rotX"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotArmX, newVal -> config.rotArmX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.rotY"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotArmY, newVal -> config.rotArmY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.render.viewmodel.arm.rotZ"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.viewmodel.desc")))
                                        .binding(0f, () -> config.rotArmZ, newVal -> config.rotArmZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.01f))
                                        .build())
                                .build())
                        // Low Fire
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.lowfire"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.lowfire"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.lowfire.desc")))
                                        .binding(defaults.lowFireEnabled, () -> config.lowFireEnabled, newVal -> config.lowFireEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Cape
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.cape"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.cape"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.cape.desc")))
                                        .binding(defaults.capeEnabled, () -> config.capeEnabled, newVal -> config.capeEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Hit Color
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.render.bcm"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.render.bcm"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.render.bcm.desc")))
                                        .binding(defaults.bcm, () -> config.bcm, newVal -> config.bcm = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())


                // MISC CATEGORY

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("brushclient.misc"))

                        // Elytra Swap
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.misc.elytraswap"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.misc.elytraswap"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.misc.elytraswap.desc")))
                                        .binding(defaults.elytraswap, () -> config.elytraswap, newVal -> config.elytraswap = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Anti RP
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.misc.antirp"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.misc.antirp"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.misc.antirp.desc")))
                                        .binding(defaults.antiRP, () -> config.antiRP, newVal -> config.antiRP = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Hide Screens
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.misc.hidescreens"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.misc.hidescreens"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.misc.hidescreens.desc")))
                                        .binding(defaults.hideScreens, () -> config.hideScreens, newVal -> config.hideScreens = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Hide Name
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.misc.hidename"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.misc.hidename"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.misc.hidename.desc")))
                                        .binding(defaults.hideName, () -> config.hideName, newVal -> config.hideName = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(String.class)
                                        .name(Text.translatable("brushclient.misc.hidename.fake"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.misc.hidename.desc")))
                                        .binding(defaults.fakeName, () -> config.fakeName, newVal -> config.fakeName = newVal)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .build())
                        .build())

                // HUD CATEGORY

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("brushclient.hud"))

                        // Effect Time
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.effecttime"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.effecttime"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.effecttime.desc")))
                                        .binding(defaults.effectTimeEnabled, () -> config.effectTimeEnabled, newVal -> config.effectTimeEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // DISCORD RPS
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.rpc"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.rpc"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.rpc.desc")))
                                        .binding(defaults.rpc, () -> config.rpc, newVal -> config.rpc = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // FPS
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.fps"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.fps"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(defaults.fps, () -> config.fps, newVal -> config.fps = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.fps.textshadow"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(defaults.textShadow, () -> config.textShadow, newVal -> config.textShadow = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.hud.fps.color"))
                                        .binding(defaults.fpsColor, () -> config.fpsColor, value -> config.fpsColor = value)
                                        .customController(opt -> new ColorController(opt, false))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.hud.fps.textsize"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(1f, () -> config.textSize, newVal -> config.textSize = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.fps.top"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(4, () -> config.top, newVal -> config.top = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1080)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.fps.left"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(4, () -> config.left, newVal -> config.left = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1920)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(String.class)
                                        .name(Text.translatable("brushclient.hud.fps.string"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.fps.desc")))
                                        .binding(defaults.nameFps, () -> config.nameFps, newVal -> config.nameFps = newVal)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .build())
                        // PING
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.ping"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.ping"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(defaults.ping, () -> config.ping, newVal -> config.ping = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.ping.textshadow"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(defaults.pingShadow, () -> config.pingShadow, newVal -> config.pingShadow = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.hud.ping.color"))
                                        .binding(defaults.pingColor, () -> config.pingColor, value -> config.pingColor = value)
                                        .customController(opt -> new ColorController(opt, false))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.hud.ping.textsize"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(1f, () -> config.pingSize, newVal -> config.pingSize = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.ping.top"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(4, () -> config.topPing, newVal -> config.topPing = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1080)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.ping.left"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(4, () -> config.leftPing, newVal -> config.leftPing = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1920)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(String.class)
                                        .name(Text.translatable("brushclient.hud.ping.string"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(defaults.name, () -> config.name, newVal -> config.name = newVal)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .build())
                        // Coordinates
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.coords"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.coords"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.coords.desc")))
                                        .binding(defaults.coords, () -> config.coords, newVal -> config.coords = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.coords.textshadow"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.coords.desc")))
                                        .binding(defaults.coordsShadow, () -> config.coordsShadow, newVal -> config.coordsShadow = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.hud.coords.color"))
                                        .binding(defaults.coordsColor, () -> config.coordsColor, value -> config.coordsColor = value)
                                        .customController(opt -> new ColorController(opt, false))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.hud.coords.textsize"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.ping.desc")))
                                        .binding(1f, () -> config.coordsSize, newVal -> config.coordsSize = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.coords.top"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.coords.desc")))
                                        .binding(4, () -> config.topCoords, newVal -> config.topCoords = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1080)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.coords.left"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.coords.desc")))
                                        .binding(4, () -> config.leftCoords, newVal -> config.leftCoords = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1920)
                                                .step(1))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.hud.serverip"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.serverip"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.serverip.desc")))
                                        .binding(defaults.ip, () -> config.ip, newVal -> config.ip = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.hud.serverip.textshadow"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.serverip.desc")))
                                        .binding(defaults.ipShadow, () -> config.ipShadow, newVal -> config.ipShadow = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.hud.serverip.color"))
                                        .binding(defaults.ipColor, () -> config.ipColor, value -> config.ipColor = value)
                                        .customController(opt -> new ColorController(opt, false))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.hud.serverip.textsize"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.serverip.desc")))
                                        .binding(1f, () -> config.ipSize, newVal -> config.ipSize = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.serverip.top"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.serverip.desc")))
                                        .binding(4, () -> config.topIp, newVal -> config.topIp = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1080)
                                                .step(1))
                                        .build())
                                .option(Option.createBuilder(int.class)
                                        .name(Text.translatable("brushclient.hud.serverip.left"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.hud.serverip.desc")))
                                        .binding(4, () -> config.leftIp, newVal -> config.leftIp = newVal)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 1920)
                                                .step(1))
                                        .build())
                                .build())
                        .build())

                // COMBAT CATEGORY

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("brushclient.combat"))

                        // Hit Armor
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.combat.hitarmor"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.hitarmor"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.hitarmor.desc")))
                                        .binding(defaults.hitArmor, () -> config.hitArmor, newVal -> config.hitArmor = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Hit Color
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.combat.hitcolor"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.hitcolor"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.hitcolor.desc")))
                                        .binding(defaults.hitcolor, () -> config.hitcolor, newVal -> config.hitcolor = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.combat.hitcolor.color"))
                                        .binding(defaults.colorHit, () -> config.colorHit, value -> config.colorHit = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .build())
                        // Crystal Optimizer
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.combat.co"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.co"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.co.desc")))
                                        .binding(defaults.coEnabled, () -> config.coEnabled, newVal -> config.coEnabled = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        // Pearl
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.combat.pearl"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.pearl"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.pearl.desc")))
                                        .binding(defaults.pearl, () -> config.pearl, newVal -> config.pearl = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.pearl.sound"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.pearl.desc")))
                                        .binding(defaults.pearlSound, () -> config.pearlSound, newVal -> config.pearlSound = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(String.class)
                                        .name(Text.translatable("brushclient.combat.pearl.sound"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.pearl.desc")))
                                        .binding(defaults.pearlSoundId, () -> config.pearlSoundId, newVal -> config.pearlSoundId = newVal)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("brushclient.combat.pearl.size"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.pearl.desc")))
                                        .binding(1f, () -> config.pearlSize, newVal -> config.pearlSize = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0f, 5f)
                                                .step(0.01f))
                                        .build())
                                .build())
                        // Block Overlay
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("brushclient.combat.blockoverlay"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("brushclient.combat.blockoverlay"))
                                        .description(OptionDescription.of(Text.translatable("brushclient.combat.blockoverlay.desc")))
                                        .binding(defaults.bo, () -> config.bo, newVal -> config.bo = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("brushclient.combat.blockoverlay.color"))
                                        .binding(defaults.boColor, () -> config.boColor, value -> config.boColor = value)
                                        .customController(opt -> new ColorController(opt, true))
                                        .build())
                                .build())
                        .build())
        )).generateScreen(parent);
    }
}